name: Deal Tracker Automation

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours at minute 0
  workflow_dispatch:        # Allow manual runs

jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Python dependencies
        working-directory: scraper
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
          
      - name: Run Scraper
        working-directory: scraper
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}
          FIREBASE_CLIENT_CERT_URL: ${{ secrets.FIREBASE_CLIENT_CERT_URL }}
          AMAZON_ASSOCIATE_TAG: ${{ secrets.AMAZON_ASSOCIATE_TAG }}
        run: |
          if [ -n "$FIREBASE_SERVICE_ACCOUNT" ]; then
            echo "$FIREBASE_SERVICE_ACCOUNT" > serviceAccountKey.json
          fi
          python main.py
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: Configure Firebase Project
        run: |
          # Navigate to frontend directory
          cd frontend
          
          # Add project ID to firebase.json
          sed -i 's/"public": "public",/"site": "'"${{ secrets.FIREBASE_PROJECT_ID )}"'",\n    "public": "public",/' firebase.json
          
          # Verify configuration
          echo "Firebase configuration:"
          cat firebase.json
          
      - name: Deploy to Firebase
        run: |
          cd frontend
          firebase deploy --only hosting \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --non-interactive