name: Deal Tracker Automation

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours at minute 0
  workflow_dispatch:        # Allow manual runs

jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # ... other steps remain the same ...
      
      - name: Configure Firebase Project
        working-directory: ./frontend
        run: |
          # Replace placeholder in firebase.json
          sed -i "s/your-project-id/${{ secrets.FIREBASE_PROJECT_ID }}/" firebase.json
          
          # Verify configuration
          echo "Firebase configuration:"
          cat firebase.json
          
      - name: Deploy to Firebase
        working-directory: ./frontend
        run: |
          firebase deploy --only hosting \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --non-interactive